"""initial schema

Revision ID: 20260921_stage2
Revises: None
Create Date: 2026-09-21 12:53:11.134954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260921_stage2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=True, comment='DART 고유번호'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='법인명/기업명'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='상태: ACTIVE, DELISTED, MERGED'),
    sa.Column('industry_id', sa.String(length=50), nullable=True, comment='업종 분류 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_corp_code'), 'company', ['corp_code'], unique=True)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_table('macro_observation',
    sa.Column('series_id', sa.String(length=50), nullable=False, comment='FRED 시리즈 ID (FEDFUNDS, CPIAUCSL, etc.)'),
    sa.Column('observation_date', sa.Date(), nullable=False, comment='관측 기준일'),
    sa.Column('vintage_date', sa.Date(), nullable=False, comment='수정 빈티지 일자'),
    sa.Column('available_at', sa.DateTime(), nullable=False, comment='실제 공개 시각 (룩어헤드 방지용)'),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('series_id', 'observation_date', 'vintage_date')
    )
    op.create_index('idx_macro_obs_date', 'macro_observation', ['observation_date'], unique=False)
    op.create_table('filing',
    sa.Column('rcept_no', sa.String(length=14), nullable=False, comment='DART 공시 접수번호'),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('report_code', sa.String(length=50), nullable=True),
    sa.Column('correction_of', sa.String(length=14), nullable=True, comment='정정공시 대상 원공시 rcept_no'),
    sa.Column('raw_ref', sa.String(length=500), nullable=True, comment='원문 XML/문서 경로 참조'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('rcept_no')
    )
    op.create_index(op.f('ix_filing_company_id'), 'filing', ['company_id'], unique=False)
    op.create_index(op.f('ix_filing_filed_at'), 'filing', ['filed_at'], unique=False)
    op.create_table('financial_fact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False, comment='보고서 기간 (예: 2023_1Q, 2023_4Q)'),
    sa.Column('account_id', sa.String(length=100), nullable=False, comment='재무 계정 ID'),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('consolidated', sa.Boolean(), nullable=True, comment='연결 여부 (True: 연결, False: 별도)'),
    sa.Column('filed_at', sa.DateTime(), nullable=False, comment='공시/공개시점'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_fact_company_id'), 'financial_fact', ['company_id'], unique=False)
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='공급사/주체 기업 ID'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='고객사/대상 기업 ID'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='SUPPLIES_TO, CUSTOMER_OF, PARTNERS_WITH, COMPETES_WITH, OWNS, BELONGS_TO'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='proposed, verified, rejected, expired'),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True, comment='신뢰도 점수 (0.0~1.0)'),
    sa.ForeignKeyConstraint(['source_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_source_id'), 'relationship', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationship_status'), 'relationship', ['status'], unique=False)
    op.create_index(op.f('ix_relationship_target_id'), 'relationship', ['target_id'], unique=False)
    op.create_table('security',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False, comment='KOSPI, KOSDAQ'),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='종목코드 (예: 005930)'),
    sa.Column('isin', sa.String(length=20), nullable=True, comment='ISIN 표준코드'),
    sa.Column('security_type', sa.String(length=20), nullable=True, comment='COMMON(보통주), PREFERRED(우선주), ETF, ETN, SPAC'),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_company_id'), 'security', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_isin'), 'security', ['isin'], unique=False)
    op.create_index(op.f('ix_security_ticker'), 'security', ['ticker'], unique=False)
    op.create_table('daily_price',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True, comment='거래대금'),
    sa.Column('adjusted_close', sa.Numeric(precision=15, scale=2), nullable=True, comment='수정주가'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('security_id', 'trade_date')
    )
    op.create_index('idx_daily_price_date', 'daily_price', ['trade_date'], unique=False)
    op.create_table('disclosure_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filing_id', sa.String(length=14), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='SUPPLY_CONTRACT, INVESTMENT, CAPITAL_INCREASE, CB_BW, etc.'),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='계약/투자 금액'),
    sa.Column('ratio', sa.Float(), nullable=True, comment='매출/자본 대비 비율'),
    sa.Column('sentiment', sa.String(length=20), nullable=True, comment='POSITIVE, NEGATIVE, NEUTRAL'),
    sa.Column('rule_version', sa.String(length=20), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.rcept_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disclosure_event_company_id'), 'disclosure_event', ['company_id'], unique=False)
    op.create_index(op.f('ix_disclosure_event_filing_id'), 'disclosure_event', ['filing_id'], unique=False)
    op.create_table('feature_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('feature_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_snapshot_as_of_date'), 'feature_snapshot', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_feature_snapshot_security_id'), 'feature_snapshot', ['security_id'], unique=False)
    op.create_table('identifier_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False, comment='DART_CORP_CODE, KRX_TICKER, ISIN, ENG_TICKER, NAVER_CODE'),
    sa.Column('source_id_value', sa.String(length=100), nullable=False, comment='외부 식별자 값'),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='대표 식별자 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identifier_source_val', 'identifier_map', ['source', 'source_id_value'], unique=False)
    op.create_index(op.f('ix_identifier_map_company_id'), 'identifier_map', ['company_id'], unique=False)
    op.create_index(op.f('ix_identifier_map_security_id'), 'identifier_map', ['security_id'], unique=False)
    op.create_index(op.f('ix_identifier_map_source'), 'identifier_map', ['source'], unique=False)
    op.create_index(op.f('ix_identifier_map_source_id_value'), 'identifier_map', ['source_id_value'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False, comment='5d, 20d, 60d'),
    sa.Column('probability', sa.Float(), nullable=False, comment='상승 확률 (0.0~1.0)'),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_as_of_date'), 'prediction', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_prediction_security_id'), 'prediction', ['security_id'], unique=False)
    op.create_table('relationship_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.String(length=14), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False, comment='관계 증거 원문 발췌 텍스트'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='문서 내 위치 (표/단락)'),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.rcept_no'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_evidence_filing_id'), 'relationship_evidence', ['filing_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_relationship_id'), 'relationship_evidence', ['relationship_id'], unique=False)
    op.create_table('score_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=20), nullable=False, comment='5d, 20d, 60d'),
    sa.Column('component', sa.JSON(), nullable=False, comment='하위 6개 점수 breakdown (Macro, Industry, Fundamental, Momentum, Disclosure, Chain)'),
    sa.Column('total', sa.Float(), nullable=False, comment='Alpha Score (0~100)'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='점수 신뢰도 (0~1.0)'),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_snapshot_as_of_date'), 'score_snapshot', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_score_snapshot_security_id'), 'score_snapshot', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_snapshot_security_id'), table_name='score_snapshot')
    op.drop_index(op.f('ix_score_snapshot_as_of_date'), table_name='score_snapshot')
    op.drop_table('score_snapshot')
    op.drop_index(op.f('ix_relationship_evidence_relationship_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_filing_id'), table_name='relationship_evidence')
    op.drop_table('relationship_evidence')
    op.drop_index(op.f('ix_prediction_security_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_as_of_date'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_identifier_map_source_id_value'), table_name='identifier_map')
    op.drop_index(op.f('ix_identifier_map_source'), table_name='identifier_map')
    op.drop_index(op.f('ix_identifier_map_security_id'), table_name='identifier_map')
    op.drop_index(op.f('ix_identifier_map_company_id'), table_name='identifier_map')
    op.drop_index('idx_identifier_source_val', table_name='identifier_map')
    op.drop_table('identifier_map')
    op.drop_index(op.f('ix_feature_snapshot_security_id'), table_name='feature_snapshot')
    op.drop_index(op.f('ix_feature_snapshot_as_of_date'), table_name='feature_snapshot')
    op.drop_table('feature_snapshot')
    op.drop_index(op.f('ix_disclosure_event_filing_id'), table_name='disclosure_event')
    op.drop_index(op.f('ix_disclosure_event_company_id'), table_name='disclosure_event')
    op.drop_table('disclosure_event')
    op.drop_index('idx_daily_price_date', table_name='daily_price')
    op.drop_table('daily_price')
    op.drop_index(op.f('ix_security_ticker'), table_name='security')
    op.drop_index(op.f('ix_security_isin'), table_name='security')
    op.drop_index(op.f('ix_security_company_id'), table_name='security')
    op.drop_table('security')
    op.drop_index(op.f('ix_relationship_target_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_status'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_source_id'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_index(op.f('ix_financial_fact_company_id'), table_name='financial_fact')
    op.drop_table('financial_fact')
    op.drop_index(op.f('ix_filing_filed_at'), table_name='filing')
    op.drop_index(op.f('ix_filing_company_id'), table_name='filing')
    op.drop_table('filing')
    op.drop_index('idx_macro_obs_date', table_name='macro_observation')
    op.drop_table('macro_observation')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_corp_code'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
